### ISSUE TITLE
preprocessing of Input images

### ISSUE THREAD

**Issue by qwfyuestc** [pboutinaud/SHIVA_PVS#2]
Dear author,

I am very interested in your method and want to apply it to my data. Could you give a detailed description of the preprocessing steps for you input images? Based on your description in your paper, I cannot figure out the appropriate preprocessing for my data. Could you give example code for the proprocessing of T1 images and also for T1+T2 images?

Thanks a lot.

Best.

**Comment by pboutinaud** [comment]
Hello,
We are working on providing a full containerized workflow for preprocessing + segmentation, but we had to change some steps since they were using tools with a propriatory licence, we are currently validating a workflow that can be published with the correct licence rights, it should be available in a few weeks.

Below is a description of the preprocessing steps by its main programmer , hope this help.

There are four main steps for preprocessing input images : conforming the image using the ‘conform’ function from the Nibabel library, intensity normalization, a thresholding step, and a cropping step. 
« nibabel.processing.conform » function resample a 3D image to a target size and voxel size while reorienting it to a new orientation. The function takes in a 3D image and resampled it to a target size specified by « out_shape » parameter with voxels of size parameters. The function then calculates a transformation matrix to reorient the image and applies it to the input image. The function then rescales the affine matrix of the reoriented image to match the new voxel size and target size. Finally, the function uses the « nibabel.processing.resample_from_to » function to resample the input image to the target size and voxel size with the specified interpolation order and constant value outside the boundaries of the input image. 

In the second stage, the voxel intensity normalization function takes a Nifti1Image as input and processes it by first removing values above the 99th percentile to avoid hot spots, setting values below 0 to 0, and setting values above 1.3 to 1.3. It then normalizes the data between 0 and 1. If a brain mask image is provided, the percentile value is calculated only on the brain region. 

For the third step, threshold function is used to create a brain mask. The mask is created by setting all values in the image below a certain threshold to zero. The arguments for the function include the threshold value which should be an appropriate value to select mostly brain tissue and remove background. 

In the last step, ‘crop’ function crops the input image based on the mask. The dimensions arguments is used to define the size of the cropped image. The function first reorients image to match the standard orientation of the image axes (‘RAS’). If brain mask is provided, the function calculates the center of mass of the mask and crops the input image based on the center.  If brain mask not provided, the center of the cropped image is calculed using the origin of the image coordinate system (by default) or the center of the image (default is set to ‘ijk’). Next, it calculates the bounding box coordinates based on the specified dimensions. Finally, it crops the input image (slicing array numpy) based on the bounding box coordinates and returns the cropped image along with the crop center.

**Comment by qwfyuestc** [comment]
Thanks for the details.
Also it is good to hear that a containerized work flow will be available in a few weeks. Looking forword to your package. 
Could you please send me a link if it is available. Thanks a lot. 

Yuanchao

**Comment by JianCheng-Wu-doctor** [comment]
Thanks for the details.
I wonder if you have sorted out your workflow. 
I am looking forward to your sharing. Thank you.

JianCheng

**Comment by farhatnadim** [comment]
Any updates on the container?

**Comment by pboutinaud** [comment]
Hello,
Sorry for the delays on providing a container for the preprocessing steps, there are a lot of IP issues with a lot of interested parties...

**Comment by pboutinaud** [comment]
The preprocessing workflow is now available here [SHiVAi](https://github.com/pboutinaud/SHiVAi)

**Comment by JianCheng-Wu-doctor** [comment]
Thank you for your reply and the contribution of your team in this matter.



At 2024-10-23 21:38:06, "Philippe Boutinaud" ***@***.***> wrote:

The preprocessing workflow is now available here SHiVAi
